### ISSUE TITLE
Doesn't seem to work with `@stencil/core@0.18.1`

### ISSUE THREAD

**Issue by chris-dura** [nisheed2440/stencil-storybook-wrapper#5]
When I run `npx stencil-storybook-wrapper` with a stencil `0.18.0` project, this wrapper seems to work, but fails when I run it on a vanilla stencial `0.18.1` project:

```shell
cd stencil-0-18-1
npx stencil-storybook-wrapper

Stencil Storybook Wrapper ERROR:

spawn /Users/CDura/code/stencil-0-18-1/node_modules/stencil-storybook-wrapper/node_modules/.bin/plop ENOENT
```

**Comment by Nightbr** [comment]
Hey, 
the trick I did is to run `npx stencil-storybook-wrapper ` on 0.18.0 stenciljs project and update stenciljs to 0.18.1 after. Works fine this way, but there is still an issue for sure...

**Comment by nisheed2440** [comment]
hi @chris-dura, Thanks for raising the issue, sorry havent reverted in a while, I will have a look at it over the weekend :)

Cheers

**Comment by nisheed2440** [comment]
<img width="884" alt="Screen Shot 2019-04-16 at 11 39 07 PM" src="https://user-images.githubusercontent.com/3470465/56249181-b9390100-60a2-11e9-86c3-a35d2a5dc4d7.png">
<img width="882" alt="Screen Shot 2019-04-16 at 11 40 53 PM" src="https://user-images.githubusercontent.com/3470465/56249182-b9d19780-60a2-11e9-9125-9beec8e31a94.png">

Unable to replicate this issue with version 1.2.0

**Comment by Buslowicz** [comment]
I have the same issue with @stencil/core@1.0.7, both with npx and after installing as global. Could the issue be reopened, or could somebody explain how to fix this issue?

**Comment by melvinwallerjr** [comment]
Creating a new project. This ticket was closed six months ago but the issue does not appear to be corrected. Using current builds as of today with Node v12.4.0

"@stencil/core": "^1.3.3",
"@storybook/html": "^5.2.5",

Stencil Storybook Wrapper ERROR:

spawn C:\DRIVERS\nvm\v12.4.0\node_modules\stencil-storybook-wrapper\node_modules\.bin/plop ENOENT

**Comment by cosmin-seviciu** [comment]
Same thing happens to me too, any ideas what to do?
