### ISSUE TITLE
Scoped package name breaks Stencil config

### ISSUE THREAD

**Issue by dougestey** [nisheed2440/stencil-storybook-wrapper#6]
Per this line in the config: https://github.com/nisheed2440/stencil-storybook-wrapper/blob/44d0a3db4195a93acb544ec4760111f5135b47af/source/templates/stencil.config.hbs#L49

If the `package.json` name field is a scoped package, this breaks the build. Not a huge issue for me, as I worked around it by skipping the `name` import here in my local config, but figured I'd let you know nonetheless :)

Seriously great work on this. It's really impressive.

**Comment by nisheed2440** [comment]
Thanks for raising the issue @dougestey. Will have look at it as soon as I can.

**Comment by nisheed2440** [comment]
fixed is version 1.3.1
