### ISSUE TITLE
Update src/index.html issue?

### ISSUE THREAD

**Issue by justindasilva** [nisheed2440/stencil-storybook-wrapper#8]
Ah jeez, I realize now I maybe should have posted my issue here first before the storybook github. Either way, I'll link to it from here. I'm not sure if the issue is with this package, or with storybook itself though.
https://github.com/storybookjs/storybook/issues/7168

**Comment by justindasilva** [comment]
@nisheed2440 Any ideas on what is going on here?

**Comment by shanmugapriyaEK** [comment]
Hi Team,
I do face the same issue. I followed the exact steps as said. 

I could not see the components preview, Instead I get the error message

**Comment by nisheed2440** [comment]
Closed by PR -> https://github.com/nisheed2440/stencil-storybook-wrapper/pull/9
